[package]
name = "zcore"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = "0.7"
downcast-rs = { version = "1.2.0", default-features = false }